### ISSUE TITLE
Content-Security-Policy (CSP) violations

### ISSUE THREAD

**Issue by koenpunt** [colszowka/simplecov-html#50]
It's currently not possible to use the HTML output without using at least 

```
script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline';
```

Which isn't desired, and requires extra configuration when setting up a coverage page in Jenkins

**Comment by bf4** [comment]
@koenpunt could you give more information about the error you're seeing and how we might reproduce it? Thanks.

**Comment by koenpunt** [comment]
I did setup Jenkins with the doclinks plugin so the coverage report is visible from within jenkins. However, due to the default CSP of Jenkins, the coverage report can't load certain javascript and css sources, required to correctly display the page. 

This can be fixed by making the CSP rule less strict, but there are also certain optimizations which can done in this gem.

**Comment by PragTob** [comment]
Merged and eleased soon.
