### ISSUE TITLE
Reuse of simplecov-html for utPLSQL v3

### ISSUE THREAD

**Issue by jgebal** [colszowka/simplecov-html#52]
Hi @colszowka 
I'd like to reuse your simplecov-html project and port it onto Oracle PLSQL for Oracle code coverage reporting with [utPLSQL v3](https://github.com/utPLSQL/utPLSQL).
Would you be OK with that? There would still be a footer pointing to simplecov-html project as the original source for the report.

**Comment by PragTob** [comment]
Hi @jgebal sorry for never checking in here.

I hope you just went ahead and did it. It's MIT License to knock yourself out: https://github.com/colszowka/simplecov-html/blob/master/LICENSE

Some attribution is nice, but frankly I think there are nicer and more modern HTML formatters for coverage but still feel free to use this one :)

**Comment by jgebal** [comment]
Thanks,
we're using your work.
Each HTML coverage report has a back-reference to the source project:
Like here - http://utplsql.org/utPLSQL-coverage-html/
We've placed assets as a separate project:
https://github.com/utPLSQL/utPLSQL-coverage-html
