### ISSUE TITLE
HTML report not generated not every time

### ISSUE THREAD

**Issue by Yoshiji** [colszowka/simplecov-html#62]
I am having a strange issue where the report in the HTML format is not created every time my test suite is ran. Even though I run `rake test` several times a day, my `index.html` report is 6 days old and I can't seem to have it refreshed with my latest run data.

In the `test_helper.rb`, I have:
```ruby
require 'simplecov'
SimpleCov.command_name 'test:unit'
SimpleCov.coverage_dir('coverage/api/unit')
```

And my `.simplecov` file contains:
```ruby
# rubocop:disable Style/FileName
require 'simplecov-lcov'
require 'simplecov-summary'

SimpleCov.coverage_dir('coverage/api')
SimpleCov.maximum_coverage_drop(0.5)

SimpleCov::Formatter::LcovFormatter.config.report_with_single_file = true
SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::LcovFormatter,
  SimpleCov::Formatter::SummaryFormatter
])

SimpleCov.profiles.define('adgear') do
  load_profile('rails')
  # [ bunch of regular add_filter and add_group('Some Name', 'some/path')
end

SimpleCov.start('adgear')
# rubocop:enable Style/FileName
```

When I try to use `SimpleCov.at_exit {  }` block, it is not executed (I tried raising an error in this block, output a `hello_world`, write a file, but nothing is executed from my custom block).

Using:
- `simplecov-0.16.1`
- `simplecov-html-0.10.2`

**Comment by PragTob** [comment]
Same questions as in colszowka/simplecov#685 basically :)

**Comment by PragTob** [comment]
This is a sibling issue in simplecov itself and the PR for that is _almost_ merged --> closing
