### ISSUE TITLE
Please publish new gem with updated .rubocop.yml

### ISSUE THREAD

**Issue by jcraigk** [colszowka/simplecov-html#68]
See screenshot below from Travis, which is showing deprecated Rubocop rules in the latest published gem (v.0.10.2):

<img width="1195" alt="Screen Shot 2019-08-02 at 10 33 54 PM" src="https://user-images.githubusercontent.com/104095/62407980-1e433480-b576-11e9-9bd5-71caa5df0834.png">

This causes hard failures in dependent apps that require modern (>= ~v.0.74) Rubocop compliance during builds.

It appears that the necessary updates to the `.rubocop.yml` file have been made in the master branch, but a new gem version has not been published.  Please publish an updated version to fix the deprecation warnings and hard failure.  Thanks.

**Comment by PragTob** [comment]
Hi there,

thanks for the report I'll try to get to it. It's curious though that dependencies would fail on that, imo that's a problem of the rubocop configuration it shouldn't look in `vendor`.

Still, just removing the `.rubocop.yml` from the package should fix that.

**Comment by jcraigk** [comment]
Right, excluding `vendor/**/*` fixes it in the short term.  Thanks!

**Comment by PragTob** [comment]
I mean, not just short term but long term imo. You don't want to have rubocop running and reporting errors on those. Also you don't want to add unnecessary time to your rubocop run as you can't fix them either way :)

We once sped up our rubocop run tremendously by just telling it to look at app/config/spec/features etc.

That said I'll still push a fix of course, I'm sadly way too busy these days but pinky promise if not please ping me again in a wekk

**Comment by PragTob** [comment]
Also the beta is released and I think this can now be closed. A full release should also not be too far away.
