### ISSUE TITLE
Wrong sorting for coverage

### ISSUE THREAD

**Issue by PragTob** [colszowka/simplecov-html#79]
It seems that coverage percents aren't correctly sorted according to their float value but rather treated as strings as reported over here: https://github.com/colszowka/simplecov/issues/781#issuecomment-572010578

![example wrong sorting](https://user-images.githubusercontent.com/5091/71975016-49ac0880-3213-11ea-80b3-d1c0cca05c14.png)

we should fix that :)

**Comment by klyonrad** [comment]
Works on the most recent version of simplecov (not beta)

Oh Jeez, the project also used JQuery-DataTables 😨

Maybe something that in the values that trips aup the automatic type detection from datatables. See https://datatables.net/reference/option/columns.type

(the packaged version of the package is also quite old by the way)

**Comment by PragTob** [comment]
@klyonrad what, really? o_O How in the hell would I have broken that with the branch coverage...

Yup the whole HTML is really old mostly written in good old 2011.

Thanks for the input!

**Comment by dmitry** [comment]
@PragTob `aoColumns` for `dataTable` should be reverted back: https://github.com/colszowka/simplecov-html/commit/bc11506aa8d09126034a609e157df27bdfb70d1c#diff-b6fb131d761768d224435ab049183090L13

**Comment by PragTob** [comment]
@dmitry thank you! Should have caught that in my initial review :see_no_evil: 

![IMG_20180603_163802](https://user-images.githubusercontent.com/606517/72145503-f795ef00-339a-11ea-881f-43c6db1f0364.jpg)

**Comment by dmitry** [comment]
Great, @PragTob! Thank you for the quick fix. It always can happen, anyway it's still beta and your work is really nice!

**Comment by PragTob** [comment]
Thank you for the quick spot! :ok_hand:
