### ISSUE TITLE
Regression: non-ASCII characters are broken

### ISSUE THREAD

**Issue by Tietew** [colszowka/simplecov-html#91]
When a source file includes non-ASCII characters i.e. Hiragana,
generated HTML contains source popups with broken characters.

Source:
```
MSG = "おはよう"
```

Expected: (simplecov-html 1.11.0)
```
1. MSG = "おはよう"
```

Actual: (simplecov-html 1.12.0)
```
1. MSG = "<?><?><?><?><?><?><?><?><?><?><?><?>"
```
Note: `<?>` seems to be a unicode replacement character.

**Comment by Tietew** [comment]
#86 can be reverted after above pr is merged because `line.src` is always UTF-8.

**Comment by PragTob** [comment]
Hi thanks or the error report! :green_heart: 

Will take a look!

**Comment by PragTob** [comment]
Fixed via https://github.com/colszowka/simplecov/pull/866 and thank you very much!
