### ISSUE TITLE
Disable pagination

### ISSUE THREAD

**Issue by klyonrad** [colszowka/simplecov-html#93]
The recent datatables upgrade apparently enabled pagination by default.

We don't query an servers or something and I think our browsers can handle this "big data", so I would suggest to disable paging.

Potential compromise: set the default page length to 500 or 1000 (although then the fact that there is pagination at all would not be so visible)

# Appendix

### Before

![image](https://user-images.githubusercontent.com/1453955/74948902-3b016580-53fd-11ea-92ea-1c239b70c093.png)

### After

😢 

The position of the search field is also a bit unintuitive

![image](https://user-images.githubusercontent.com/1453955/74948855-2a50ef80-53fd-11ea-8d5d-05a1f99de10b.png)

**Comment by PragTob** [comment]
:wave: 

Hi @klyonrad - wasn't pagination always activated it was just further down to the right where it was displayed?

umping the pagination limit might be a good idea anyhow. It'd also magically get rid off that "pagination doesn't work anymore" bug that I hadn't yet thought of :angel:

**Comment by PragTob** [comment]
I just tried it out and at least for 100 files pagination didn't doesn't trigger on the old version... strange I could have sworn... :thinking:

**Comment by PragTob** [comment]
Fixed through https://github.com/colszowka/simplecov-html/pull/96
