### ISSUE TITLE
Cannot refresh coverage page directly in version '0.12.0'

### ISSUE THREAD

**Issue by HansBug** [colszowka/simplecov-html#94]
In version `0.11.0`,  when I open a coverage page (with anchor, like `http://coverage.core.ips.net/#8fa08b9ca3d22133f6daaa36049fcd5a9e1ef472`), after some of the code in this page has changed, I can directly refresh the page, then the new code and coverage situation can be displayed.

But in version `0.12.0`, when I do this (something even there is no change with the code), the page will be in loading status endlessly (the progress bar will act continuously, but no code and coverage displayed). This happens in all the coverage pages.

I'm not sure whether this is a new feature in version `0.12.0` or a bug, maybe maintainers can check this?

**Comment by HansBug** [comment]
Sorry for my mistake operating. I will append some details next.

**Comment by PragTob** [comment]
Most likely a bug related to the wild JS updates. 

Might also still be deleted to the pagination, as I think datatables tries to pull something from some server.. idk.

Sorry for the mess. Hope to gradually fix all this, stick to the old version until then and sorry for the inconvenience :(

**Comment by PragTob** [comment]
Definitely not intended. Still unsure/when how this happend.

It's not related to the pagination though, even with the pagination fix I still have this behaviour sadly.

```
Error: Syntax error, unrecognized expression: a.src_link[href=#b4b6c5440441f74b61f7568511ee73b99e2b9da6]
```

Not sue what's going wrong here. If anyone wants to investigate, please do. In my mind it's either the JS updates or maybe the hiding of the container: #29 

There aren't many commits that could have broken it so a git bisect would probably also go a long way.

**Comment by HansBug** [comment]
Emmm, I did not found any javascript failure in the frontend when this happened. So I'm not sure whether this problem is caused by frontend or not, sorry for that.

**Comment by HansBug** [comment]
Some additional information for version `0.12.1` :
Problem in issue #92 is ok now, but this issue (#94) still exist. This time I find this failure in browser console(chrome) when refresh the page with anchor:

```
application.js:1 Uncaught Error: Syntax error, unrecognized expression: a.src_link[href=#39b00e29519d0795244531d8048d1be589825c0a]
    at Function.w.error (application.js:1)
    at w.tokenize (application.js:2)
    at w.select (application.js:2)
    at Function.w [as find] (application.js:1)
    at Te.fn.init.find (application.js:2)
    at new Te.fn.init (application.js:2)
    at Te (application.js:1)
    at HTMLDocument.<anonymous> (application.js:7)
    at t (application.js:2)
    at a (application.js:2)
```

Steps to reproduce this failure:

1. Open the coverage home page
2. Select one line, click it, then the coverage detail of the chosen ruby file will be displayed
3. **Press F5 (do refresh) at this moment**, then the failure above will appear

Wish these information can help you :)
